<?php
echo "<table>";
echo "<tr>";
echo "<td><b>Nombre</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='nombre'></td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Saga</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='saga'></td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Numero</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='numero'></td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Editorial</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='editorial'></td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Escritor</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='escritor'></td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Dibujante</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='dibujante'><td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Genero</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='genero'><td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Idioma</td>";
echo "</tr>";
echo "<tr>";
echo "<td><input type='text' id='idioma'><td>";
echo "</tr>";
echo "<tr>";
echo "<td><b>Rango de precio</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Desde $<input type='text' id='desde' value='0'> Hasta $<input type='text' id='hasta' value='9999999'></td>";
echo "<tr>";
echo "<td><select id='estado'>";
echo "<option value='compra'>Compra</option><option value='venta'>Venta</option><option value='reserva'>Reserva</option>";
echo "</select></td>";
//echo "<td><input type='checkbox' id='compra'>Compras  <input type='checkbox' id='venta'>Ventas  <input type='checkbox' id='reserva'>Reservas</td>";
echo "</tr>";
echo "<tr>";
echo "<td><button id='bavanzada' onclick='busquedaAvanzada()' class='botonbuscar'>Buscar</button>";
echo "</tr>";
echo "</table>";

?>
